version: '3.0'

services:
  consul:
    image: consul:1.3.0
    hostname: consulserver1
    network_mode: host
    volumes:
      - ./data/:/consul/data
      - ./consul.json/:/consul/config/consul.json
    command: agent -server -config-dir=/consul/config